### ISSUE TITLE
Using around_action to set the locale

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/rails-templates#127]
### Why

To set the locale in `before_action`, there will is a case that the I18n can't get the default locale for some request, I faced that in a project.

For more details:

- https://github.com/ruby-i18n/i18n/issues/381
- https://github.com/rails/rails/issues/34043
- https://github.com/rails/rails/pull/34356
- https://guides.rubyonrails.org/i18n.html#managing-the-locale-across-requests

### Solution

I think we should go with the Rails way, using `around_action` instead - https://guides.rubyonrails.org/i18n.html#managing-the-locale-across-requests

**Comment by malparty** [comment]
@andyduong1920 do you have more information about this case? What was the problem? In which situation was the local not assigned properly? (maybe in an Engine controller that did not inherit from the main `::ApplicationController`? 🤔 )

My case is that `around_action` is resetting the locale to the default value after the action, and this is bad with Devise flash messages when login fails: because devise redirects to the `login` page, and sets the `flash message` after the action is completed, so the locale value used will be the default one, not the current one =/ 

Thanks for your lights! 🙌

**Comment by andyduong1920** [comment]
That is the case @malparty we set the locale on before_action, but the flash message didn't get localized.
