### ISSUE TITLE
Enable public_file_server by default

### ISSUE THREAD

**Issue by gutakk** [nimblehq/rails-templates#234]
### What happened?
I'm working on Ruby Internal Certification and everything about static files work fine (my case is css file).
But when I deployed to Heroku server, Rails app not be able to find css file.

This happened because 
```
# Disable serving static files from the `/public` folder by default since
# Apache or NGINX already handles this.
config.public_file_server.enabled = ENV['RAILS_SERVE_STATIC_FILES'].present?
```

### How to fix
Just set `RAILS_SERVE_STATIC_FILES` to `true`, and you are good to go.

**Comment by olivierobert** [comment]
I don't recommend to set it by default as we don't always deploy to Heroku. Maybe that. could be part of a Heroku addon @andyduong1920 ?

**Comment by andyduong1920** [comment]
@olivierobert as default we don't have Nginx setup so the app won't return the static file. It doesn't matter where do we deploy the app (Heroku or AWS or Google cloud) because the Rails itself doesn't return the static file.

So IMO, we could enable this by default, and we can turn it off in the [Nginx addon](https://github.com/nimblehq/rails-templates/pull/232) PR
