### ISSUE TITLE
Add Makefile to build commands

### ISSUE THREAD

**Issue by hoangmirs** [nimblehq/rails-templates#348]
## Why

- Makefile helps us to build commands easily. Other templates are using it: [gin-templates](https://github.com/nimblehq/gin-templates/blob/develop/%7B%7Bcookiecutter.app_name%7D%7D/Makefile), [elixir-templates](https://github.com/nimblehq/elixir-templates/blob/680a3649dc08762882d8c02332a1f16d2f0e95a4/priv/templates/nimble_template/Makefile)
- With Makefile, we can build some basic commands e.g. `install-dependencies`, `env-setup`, `dev`, `test` so that we don't need to remember some commands in `/bin` folder. And it will be consistent with other templates as well.
 
## Who Benefits?

Rails developers

**Comment by malparty** [comment]
💯 
Can we also update the `Getting Started` wiki page accordingly, so that we do not need to fix the current issue of "Run `bundle install` first` — it occurs when following exactly the indicated steps:

![image](https://user-images.githubusercontent.com/77609814/181413306-ed6472a8-46e9-4831-b1b2-6db342b8820d.png)
